### ISSUE TITLE
camera opens in ubuntu and nothing happens

### ISSUE THREAD

**Issue by imkks** [ChakPC/Invisible_Cloak#1]
I have tried implementing on my sytem the webcam glows but nothing happens after sometime it shows not responding
![Screenshot from 2020-06-25 22-16-55](https://user-images.githubusercontent.com/52670330/85762705-a05dbe00-b731-11ea-80ac-7c09e552c1dc.png)

**Comment by ChakPC** [comment]
This error should not happen in general...but don't worry... the same error was on my system too for a different project that involved openCV....it's the Face Recognition project and you may check that from my github....it was working fine on another system and I am unaware of the real problem....I am guessing this may be something related to OS....Initially, I used this

**key_pressed = cv2.waitkey(1) &0xFF
if key_pressed == ord('q'):
       break;**

But this didn't work.....my program used to get stuck in an infinite loop for unknown reasons and I couldn't exit by pressing q
So I searched on google and found out that there is another way to break out of this loop ,i.e., **keyboard.is_pressed('q')**. For that , you have to obviously install keyboard module separately by typing 
pip install keyboard (for windows...you can get the command for linux from google)
in the terminal
So, I used that only but this time I got the same error as you are getting. 
But then I did something weird. I kept both of them.
**key_pressed = cv2.waitkey(1) &0xFF
if key_pressed == ord('q'):
       break;
if keyboard.is_pressed('q'):
       break;**
and it worked for me. I have no idea that why this worked and others didn't and I couldn't understand this. But finally I had my project working. After that I use both of them in my openCV projects...So you may follow the steps which I have used and if you are lucky then one of these steps will work for you. Otherwise, just keep searching and you will surely get something. I am closing this issue and in case if these steps don't work then you are welcome to reopen the issue and even state the solution for the same which you got...._Best of Luck :)_

**Comment by imkks** [comment]
thanx it helped in my case removing the keyboard package and keyboard.is_pressed('q') function. Very nice project with a innovative idea all the best!
